import Head from "next/head";
import A from "./A";

export default function MainContainer({ children, keywords }) {
    return (
        <>
            <Head>
                <title>Главная страница</title>
                <meta keywords={"nextjs some project " + keywords} name="description" content="Generated by create next app" />
            </Head>
            <div className="navbar">
                <A href="/" text="Главная" />
                <A href="/users" text="Пользователи" />
            </div>
            <div>
                {children}
            </div>
            <style jsx>
                {`
                    .navbar {
                        background-color: orange;
                        padding: 15px;
                    }
                    .link {
                        text-decoration: none;
                        color: white;
                        font-size: 20px;
                        margin: 10px;
                    }
                    .link a {
                        text-decoration: none;
                    }
                `}
            </style>
        </>
    )
}